package Proyect2LFP.UI;

import Proyect2LFP.Analizador.Analizador;
import Proyect2LFP.Analizador.CargarArchivo;
import javax.swing.WindowConstants;

/**
 *
 * @author jara
 */
public class JFIndex extends javax.swing.JFrame {
    String b="";
    String cargado = "";
    String analizado = "";
    CargarArchivo ca;
    Analizador anal;

    /**
     * Creates new form JFIndex
     */
    public JFIndex() {     
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaCargar = new javax.swing.JTextArea();
        btnCargar = new javax.swing.JButton();
        btnAnalizar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        AreaAnalizar = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(850, 650));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(26, 83, 102));
        jPanel1.setLayout(null);

        AreaCargar.setColumns(20);
        AreaCargar.setRows(5);
        jScrollPane1.setViewportView(AreaCargar);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 260, 330, 244);

        btnCargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyect2LFP/Images/Cargar.png"))); // NOI18N
        btnCargar.setText("Cargar Archivo");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCargar);
        btnCargar.setBounds(100, 140, 190, 60);

        btnAnalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyect2LFP/Images/Anal.png"))); // NOI18N
        btnAnalizar.setText("Analizar Archivo");
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnalizar);
        btnAnalizar.setBounds(510, 140, 190, 60);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyect2LFP/Images/Salir.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);
        btnSalir.setBounds(690, 40, 70, 60);

        AreaAnalizar.setColumns(20);
        AreaAnalizar.setRows(5);
        jScrollPane2.setViewportView(AreaAnalizar);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(450, 260, 330, 244);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 850, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        load();
    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
       ca = new CargarArchivo();
    }//GEN-LAST:event_btnAnalizarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        JFIndex jf = new JFIndex();
        jf.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaAnalizar;
    private javax.swing.JTextArea AreaCargar;
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
   public void analizar(String[] separado){
        for (int i = 0; i <= separado.length-1; i++) {
            System.out.println(separado[i]);
        }
    }
    
    public void load(){
        ca = new CargarArchivo();
        ca.verArchivo();
        cargado = ca.docCargado;
        AreaCargar.setText(cargado);
    }
}
